//
//  ProductListRouter.swift
//  SCBBuyerGuide
//
//  Created NiM on 5/27/2561 BE.
//  Copyright © 2561 NiM. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProductListRouter: ProductListWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view:ProductListViewController?) -> ProductListViewController? {
        // Change to get view from storyboard if not using progammatic UI
        let interactor = ProductListInteractor()
        let router = ProductListRouter()
        
        if let listView = view {
            let presenter = ProductListPresenter(interface: listView, interactor: interactor, router: router)
            listView.presenter = presenter
            interactor.presenter = presenter
        }
        
        router.viewController = view
        
        return view
    }
}
