//
//  ProductDetailProtocols.swift
//  SCBBuyerGuide
//
//  Created NiM on 5/27/2561 BE.
//  Copyright © 2561 NiM. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: Wireframe -
protocol ProductDetailWireframeProtocol: class {

}
//MARK: Presenter -
protocol ProductDetailPresenterProtocol: class {

    var interactor: ProductDetailInteractorInputProtocol? { get set }
    
    func requestImageList(for view:UIView) 
}

//MARK: Interactor -
protocol ProductDetailInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    
}

protocol ProductDetailInteractorInputProtocol: class {

    var presenter: ProductDetailInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func requestImageList(for itemID:String, completion:@escaping ((_ imageList:[String]?, _ errorMessage:String?) -> Void)) 
}

//MARK: View -
protocol ProductDetailViewProtocol: class {

    var presenter: ProductDetailPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func getProduct() -> Product?
    func updateImageList(imageList:[String])
    func showAlert(message:String)
}
