//
//  MainProductViewProtocols.swift
//  SCBBuyerGuide
//
//  Created NiM on 5/27/2561 BE.
//  Copyright © 2561 NiM. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: Wireframe -
protocol MainProductViewWireframeProtocol: class {
    func showProductDetail(for item: Product)
}
//MARK: Presenter -
protocol MainProductViewPresenterProtocol: class {
    func producListRequestUpdate()
    func showAlert(message:String)
    func showProductDetail(for item: Product)
}

//MARK: Interactor -
protocol MainProductViewInteractorProtocol: class {

    var presenter: MainProductViewPresenterProtocol?  { get set }
    var controllerList:[ProductListViewController]? { get set }

    func getIndex(for controller:UIViewController?) -> Int?
    func requestPage(at index:Int) -> UIViewController?
    func isLowerBound(_ index: Int) -> Bool
}

//MARK: View -
protocol MainProductViewViewProtocol: class {

  var presenter: MainProductViewPresenterProtocol?  { get set }
  
    func updateSegment(to index:Int)
    func showAlert(message:String)
    func producListRequestUpdate()
}
