//
//  MainProductViewRouter.swift
//  SCBBuyerGuide
//
//  Created NiM on 5/27/2561 BE.
//  Copyright © 2561 NiM. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainProductViewRouter: MainProductViewWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(from view:MainViewController) -> MainViewController {
        // Change to get view from storyboard if not using progammatic UI
        let interactor = MainProductViewInteractor()
        let router = MainProductViewRouter()
        let presenter = MainProductViewPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func showProductDetail(for item: Product) {
        let detailPage = ProductDetailRouter.createModule(from: StoryBoardHelper.getProductDetail())
        detailPage.product = item
        self.viewController?.navigationController?.pushViewController(detailPage, animated: true)
    }
}
